// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2020-04-06T04:31:01.544Z

const awsmobile = {
    aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
    aws_appsync_graphqlEndpoint: 'https://x6bavdhfefamlfolyzk7lsu2sm.appsync-api.us-east-1.amazonaws.com/graphql',
    aws_appsync_region: 'us-east-1',
    aws_cognito_identity_pool_id: 'us-east-1:94eaf0b6-49fd-4d88-b012-0609faf9e200',
    aws_cognito_region: 'us-east-1',
    aws_project_region: 'us-east-1',
    aws_user_files_s3_bucket: 'ai-covid-infra-userfiles',
    aws_user_files_s3_bucket_region: 'us-east-1',
    federated: {
        amazon_client_id: 'amazon-client-id',
        facebook_app_id: 'facebook-app-id',
        google_client_id: 'google-webclient-id'
    }
};

export default awsmobile;
